#!/bin/bash
#Getting the Value of the Thresholds
init() {
echo "Enter value for the Critical Threshold: "
read c
echo "Enter value for the Warning Threshold: "
read w
echo "Enter value for the Email Address: "
read e
}
init
while [ ${w} -ge ${c} ]
do
  echo "Value of Warning Threshold must not be greater than or equal to Critical Threshold"
  init
done
  echo "Memory_Check -c ${c}, -w ${w}, -e ${e}"
#Comparing UsedMem with Thresholds in %
um=$( free -m | grep Mem: | awk '{ printf "%d\n", $3*100/$2 }' )
sleep 1
if [$um -ge $c]
  then echo "Memory Usage reach Critical Threshold"
  else if [ $um -ge $w && $um -le $c ]
    then echo "Memory Usage reach Warning Threshold"
    else if [ $um -lt $w ]
      then echo "Memory Usage at Normal state"
    fi
  fi
fi

